# -*- coding: utf-8 -*-
{
    'name': 'HR Recruitment & Onboarding Pro',
    'version': '1.0.0',
    'category': 'Human Resources/Recruitment',
    'summary': 'Full recruitment pipeline, onboarding, AI candidate matching',
    'author': 'Anil K',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'hr',
        'hr_recruitment',
        'calendar',
        'mail',
        'portal',
        'website',
        'base_automation',
        'sms',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/recruitment_stages.xml',
        'data/onboarding_stages.xml',
        'data/mail_templates.xml',
        'data/automation_rules.xml',
        'data/social_post_templates.xml',
        'views/menu_items.xml',
        'views/hr_job_views.xml',
        'views/hr_applicant_views.xml',
        'views/hr_onboarding_views.xml',
        'views/approval_views.xml',
        'views/res_config_settings_views.xml',
        'views/hr_employee_views.xml',
        'wizards/make_offer_wizard_views.xml',
        'wizards/import_linkedin_views.xml',
        'templates/portal_templates.xml',
        'templates/website_jobs.xml',
        'report/report_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hr_recruitment_onboarding/static/src/css/recruitment.css',
            'hr_recruitment_onboarding/static/src/js/recruitment_dashboard.js',
            'hr_recruitment_onboarding/static/src/js/ai_scoring.js',
        ],
        'web.assets_frontend': [
            'hr_recruitment_onboarding/static/src/css/portal.css',
        ],
    },
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
